http:
  port: 8080
  hostname: 0.0.0.0


admin:
  port: 9876
  host: localhost


policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit


apiEndpoints:

  web0:
    host: '*'
    methods: [ 'GET' ]
    paths:
      - '/web0'
      - '/web0/*'

  web1:
    host: '*'
    methods: [ 'GET' ]
    paths: 
      - '/web1'
      - '/web1/*'

  web2:
    host: '*'
    methods: [ 'GET' ]
    paths: 
      - '/web2'
      - '/web2/*'


serviceEndpoints:

  app:web-multi:
    urls:
      - 'http://learning_express_gateway_go_dummy_http_1/'
      - 'http://learning_express_gateway_go_dummy_http_2/'

  app:web-server-1:
    url: 'http://learning_express_gateway_go_dummy_http_1/'

  app:web-server-2:
    url: 'http://learning_express_gateway_go_dummy_http_2/'


pipelines:

  pipe-web0:
    apiEndpoints:
      - web0
    policies:
      - expression:
        - action:
            jscode: 'req.url = req.url.replace(/^\/web0/, ""); '
      - proxy:
        - action:
            serviceEndpoint: app:web-multi
            strategy: round-robin

  pipe-web1:
    apiEndpoints:
      - web1
    policies:
      - expression:
        - action:
            jscode: 'req.url = req.url.replace(/^\/web1/, ""); '
      - proxy:
        - action:
            serviceEndpoint: app:web-server-1

  pipe-web2:
    apiEndpoints:
      - web2
    policies:
      - expression:
        - action:
            jscode: 'req.url = req.url.replace(/^\/web2/, ""); '
      - proxy:
        - action:
            serviceEndpoint: app:web-server-2
