version: '3.7'

services:
    application:
        container_name: ${COMPOSE_PROJECT_NAME}_application
        user: ${DEVELOPER_UID}:${DEVELOPER_UID}
        build:
            context: node
            target: ${BUILD_TARGET}
            args:
                - DEVELOPER_UID
                - BASE_IMAGE
        environment:
            - LOG_LEVEL=${LOG_LEVEL} # DOC https://www.express-gateway.io/docs/runtime/
        command: bash -c "cd gateway && npm install && npm start"
        ports:
            - 8080:8080 # http
            - 8443:8443 # https
            - 9876:9876 # admin
        tty: true
        volumes:
            - ../:/app
            - ../logs:/root/.npm/_logs
        networks:
            devapp: ~

    go_dummy_http_1:
        container_name: ${COMPOSE_PROJECT_NAME}_go_dummy_http_1
        image: mmalessa/go-dummy-http:1.0.0
        environment:
            - APP_INSTANCE=http1
        ports:
            - 8081:80
        networks:
            devapp: ~

    go_dummy_http_2:
        container_name: ${COMPOSE_PROJECT_NAME}_go_dummy_http_2
        image: mmalessa/go-dummy-http:1.0.0
        environment:
            - APP_INSTANCE=http2
        ports:
            - 8082:80
        networks:
            devapp: ~

networks:
    devapp:
        name: devapp

